echo 安装 Kotori 中...
npm install kotori-bot
echo 安装基础插件中...
npm install @kotori-bot/kotori-plugin-access @kotori-bot/kotori-plugin-adapter-sandbox @kotori-bot/kotori-plugin-adapter-cmd @kotori-bot/kotori-plugin-alias @kotori-bot/kotori-plugin-core @kotori-bot/kotori-plugin-helper @kotori-bot/kotori-plugin-i18n-command @kotori-bot/kotori-plugin-menu @kotori-bot/kotori-plugin-status @kotori-bot/kotori-plugin-webui 
echo 安装完成